//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long NewId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public string Image { get; set; }
    
        public virtual User User { get; set; }
    }
}
