//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OderDetail
    {
        public int Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public long OrdId { get; set; }
        public long SpId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual SpecificProduct SpecificProduct { get; set; }
    }
}
